const AuthenticationController = require('./controllers/AuthenticationController')
const AuthenticationControllerPolicy = require('./policies/AuthenticationControllerPolicy')
const EventoController = require('./controllers/EventoController')
const InscricaoController = require('./controllers/InscricaoController')

module.exports = (app) => {
  app.post('/register', AuthenticationControllerPolicy.register, AuthenticationController.register)
  app.post('/login', AuthenticationController.login)
  app.put('/user/:userId', AuthenticationController.put)
  app.get('/user/:userId', AuthenticationController.show)
  app.get('/users', AuthenticationController.index)
  app.get('/eventos', EventoController.index)
  app.post('/eventos', EventoController.post)
  app.get('/eventos/:eventoId', EventoController.show)
  app.get('/eventosUsuario/:userId', EventoController.getUser)
  app.put('/eventos/:eventoId', EventoController.put)
  app.delete('/eventos/:eventoId', EventoController.delete)
  app.post('/inscricao', InscricaoController.post)
  app.put('/inscricao/:inscricaoId', InscricaoController.put)
  app.get('/inscricaoUsuario/:userId', InscricaoController.getUser)
  app.get('/inscricaoEvento/:eventoId', InscricaoController.getEvento)
  app.get('/inscricoesDono/:userId', InscricaoController.getOwner)
  app.post('/inscricao', InscricaoController.post)
  app.delete('/inscricao/:inscricaoId', InscricaoController.delete)
  app.post('/geraCertificado/:inscricaoId', InscricaoController.geraCertificado)
  app.get('/validaCertificado/:desHash', InscricaoController.validaCertificado)
  app.put('/checkin/:inscricaoId', InscricaoController.checkin)
}
