package screens;

import entitys.User;
import java.awt.event.KeyEvent;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

public class FormLogin extends javax.swing.JFrame {

    private static List<User> ListUser;

    public static List<User> getLsUser() {
        return ListUser;
    }

    public static void setListUser(List<User> ListUser) {
        FormLogin.ListUser = ListUser;
    }

    public static User procuraUser(String email) {
        User user = null;
        for (User u : ListUser) {
            if (u.getEmail().equals(email)) {
                user = u;
            }
        }
        return user;
    }

    public String hash(String password) {
        return BCrypt.hashpw(password, BCrypt.gensalt(10));
    }

    public String md5(String password) throws NoSuchAlgorithmException {
        MessageDigest md = MessageDigest.getInstance("MD5");
        md.update(password.getBytes());
        byte[] hashMd5 = md.digest();
        return String.valueOf(hashMd5);
    }

    public boolean verifyHash(String password, String hash) {
        return BCrypt.checkpw(password, hash);
    }

    //private final AuthDao auth;
    //private final Functions functions;
    public FormLogin() {
        initComponents();

        //auth = new AuthDao();
        //functions = new Functions();
        // functions.setIcon(this);
        this.setTitle("Autenticação");

        jtfUsername.setText("saargov97@gmail.com");
        jtfPassword.setText("12345678");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LateralDireita = new javax.swing.JPanel();
        Centro = new javax.swing.JPanel();
        jBtnLogin = new javax.swing.JButton();
        jtfPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autentificação");
        setResizable(false);

        LateralDireita.setBackground(new java.awt.Color(72, 70, 70));
        LateralDireita.setLayout(new java.awt.BorderLayout());
        getContentPane().add(LateralDireita, java.awt.BorderLayout.LINE_START);

        Centro.setBackground(new java.awt.Color(72, 70, 70));

        jBtnLogin.setBackground(new java.awt.Color(162, 157, 157));
        jBtnLogin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnLogin.setForeground(new java.awt.Color(1, 1, 1));
        jBtnLogin.setText("Acessar");
        jBtnLogin.setToolTipText("Acessar");
        jBtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLoginMouseClicked(evt);
            }
        });
        jBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginActionPerformed(evt);
            }
        });
        jBtnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnLoginKeyPressed(evt);
            }
        });

        jtfPassword.setBackground(new java.awt.Color(72, 70, 70));
        jtfPassword.setForeground(new java.awt.Color(255, 255, 255));
        jtfPassword.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuário:");

        jtfUsername.setBackground(new java.awt.Color(72, 70, 70));
        jtfUsername.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfUsername.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Autenticação");

        javax.swing.GroupLayout CentroLayout = new javax.swing.GroupLayout(Centro);
        Centro.setLayout(CentroLayout);
        CentroLayout.setHorizontalGroup(
            CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
            .addGroup(CentroLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CentroLayout.setVerticalGroup(
            CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentroLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(Centro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLoginMouseClicked

    }//GEN-LAST:event_jBtnLoginMouseClicked

    private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginActionPerformed
        if (jtfUsername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o email de usuário!");
        } else if (String.valueOf(jtfPassword.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a senha!");
        } else if (jtfUsername.getText().equals("admin")) {
            FormMenu principal = new FormMenu(new User());
            principal.setNameUser("Administrador");
            principal.setVisible(true);
        } else {
            User user = procuraUser(jtfUsername.getText());
            String senha = String.valueOf(jtfPassword.getPassword());
            String genHash = hash("12345678");
            // previously been hashed
            if (BCrypt.checkpw(user.getPassword(), genHash)) {
                System.out.println("It matches");
            } else {
                System.out.println("It does not match");
            }
            //System.out.println(user.getPassword2());
            //System.out.println(senha);
            if ((user == null) || (!user.getPassword2().equals(senha))) {
                JOptionPane.showMessageDialog(null, "Nome de usuário ou senha não conferem. Por favor, verifique!", "Erro", JOptionPane.ERROR_MESSAGE, null);
            } else {
                FormMenu principal = new FormMenu(user);
                principal.setVisible(true);
                this.dispose();
            }

            /* user = auth.login(user);

             if (auth.getResponseCode() < 400) {
             
             } else if (auth.getResponseCode() == 401 || auth.getResponseCode() == 403) {
             JOptionPane.showMessageDialog(null, "Nome de usuário ou senha não conferem. Por favor, verifique!", "Erro", JOptionPane.ERROR_MESSAGE, null);
             } else {
             JOptionPane.showMessageDialog(null, "Erro não identificado ao realizar a autenticação. Por favor, verifique!", "Erro", JOptionPane.ERROR_MESSAGE, null);
             }*/
        }
    }//GEN-LAST:event_jBtnLoginActionPerformed

    private void jBtnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jBtnLogin.doClick();
        }
    }//GEN-LAST:event_jBtnLoginKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Centro;
    private javax.swing.JPanel LateralDireita;
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jtfPassword;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
